### ISSUE TITLE
application.yml中的namespace有误，正确的是 namespaceid 值

### ISSUE THREAD

**Issue by geligaoli** [dromara/RuoYi-Cloud-Plus#1]
配置项中：

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}

实际上，namespace: 这里需要是namespaceid。nacos自动生成的一大串字符的那个。

**Comment by JavaLionLi** [comment]
有没有可能 id可以自定义 写啥都行
